{
 "title": "overview",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "label": "Host", "query": { "query": "label_values(up, host)" } }
  ]
 },
 "panels": [
  { "title": "Neues Panel", "type": "grafana-clock-panel", "gridPos": { "h": 5, "w": 13, "x": 0, "y": 0 } },
  { "title": "Important", "type": "dashlist", "gridPos": { "h": 6, "w": 5, "x": 0, "y": 5 } },
  { "title": "Neues Panel", "type": "alertlist", "gridPos": { "h": 6, "w": 19, "x": 5, "y": 5 } },
  { "title": "Overview $host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }, "repeat": "host" },
  {
   "title": "Exporter",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "min(up{host=\"$host\"}) by (job, instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{host=\"$host\"}\n-\nnode_boot_time_seconds{host=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(up{host=\"$host\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HDD",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{host=\"$host\", mountpoint=\"/\"}\n-\nnode_filesystem_avail_bytes{host=\"$host\", mountpoint=\"/\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_filesystem_avail_bytes{host=\"$host\", mountpoint=\"/\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg by (host) (rate(node_cpu_seconds_total{mode=\"idle\", host=\"$host\"}[1m])) * 100)",
     "legendFormat": "CPU /s"
    },
    {
     "expr": "node_memory_MemTotal_bytes{host=\"$host\"}",
     "legendFormat": "Memory total"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{host=\"$host\"}",
     "legendFormat": "Memory available"
    }
   ]
  }
 ]
}